package com.example.medoblock.features.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


val LightGreen10 = Color(0xFFD7FFEB)
val gray1 = Color(0xFFC4C4C4)
val chatGreen = Color(0xFF4974E9)

val lightBlack = Color(0xFF333333)
val black_4 = Color(0xFF757575)

val green1 = Color(0xFF27AE61)
val green2 = Color(0xFF4CD964)
val gray30 = Color(0xFFA8A8A8)
val dimGrayTextColor = Color(0xFF5F6368)
val grayTextColor = Color(0xFFA8A8A8)
val dividerColor = Color(0xFFCCCCCC)
val dividerColor2 = Color(0xFFE9E5DF)
val redA1 = Color(0xFFEA5A34)


val gray20 = Color(0xFFBABECC)
val lightGrayBackground = Color(0xFFE5E5E5)
val orange1 = Color(0xFFF59A31)
val blueTextColor = Color(0xFF2975AA)
val purpleTextColor = Color(0xFF8129AA)
val input_bottom_border = Color(0xFFF6F6F6)
val info_sky = Color(0xFF4184B2)
val orange2 = Color(0xFFFFA033)
val purple_heart = Color(0xFFEE2A7B)
val purple10 = Color(0xFF8327AE)
val dangerRed = Color(0xFFDF3725)
val Red10 = Color(0xFFDF3725)
val gradientLightRed1 = Color(0xFFFFF0F0)
val gradientLightRed2 = Color(0xFFFFD9D9)
val gradientLightGreen1 = Color(0xFFDEFDEB)
val gradientLightGreen2 = Color(0xFF8DECB5)
val gradientLightOrange1 = Color(0xFFFFFCEA)
val gradientLightOrange2 = Color(0xFFFFF8C2)
val dimGrayColor = Color(0xFFC4C4C4)
val lightYellowBackground = Color(0x80FFF7C6)
val warningYellow = Color(0xFFefcc00)
val black = Color(0xFF000000)


val md_theme_light_primary = Color(0xFF8B4483)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F4)
val md_theme_light_onPrimaryContainer = Color(0xFF380037)
val md_theme_light_secondary = Color(0xFF00687B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFAEECFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F26)
val md_theme_light_tertiary = Color(0xFF815344)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onTertiaryContainer = Color(0xFF321207)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEEDEE7)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFABF1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8B4483)
val md_theme_light_outlineVariant = Color(0xFFD1C2CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFABF1)
val md_theme_dark_onPrimary = Color(0xFF551351)
val md_theme_dark_primaryContainer = Color(0xFF702C6A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F4)
val md_theme_dark_secondary = Color(0xFF56D6F5)
val md_theme_dark_onSecondary = Color(0xFF003641)
val md_theme_dark_secondaryContainer = Color(0xFF004E5D)
val md_theme_dark_onSecondaryContainer = Color(0xFFAEECFF)
val md_theme_dark_tertiary = Color(0xFFF5B8A6)
val md_theme_dark_onTertiary = Color(0xFF4C261A)
val md_theme_dark_tertiaryContainer = Color(0xFF663C2E)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C2CB)
val md_theme_dark_outline = Color(0xFF9A8D95)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFF8B4483)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFABF1)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF8B4483)